/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
 * Generated on: 10-Nov-2023 22:07:19
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /run/media/sp6gk/890dfc73-b3c6-4690-879b-6c7b7666e4ea/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
   0.004144596402,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
   0.001148197334,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
     0.8912509084,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.947644949,   0.9642233253 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.910920978,   0.9155138135 
  },
  {
                1,              0,              0 
  }
};
